version: '3'

services:
  mcp-server:
    build: .
    container_name: mcp-server-qdrant
    environment:
      - QDRANT_URL=http://qdrant-v8gc8cc4sk80o444ccck0gkg.178.16.129.71.sslip.io
      - QDRANT_API_KEY=obuONHxVHnSKivuN9Q5xqZGqtERfc2KM
      - COLLECTION_NAME=ClaudeCollection
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/", "||", "echo", "Server not ready yet"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 20s