version: '3'

services:
  mcp-server:
    build: .
    container_name: mcp-server-qdrant
    environment:
      - QDRANT_URL=http://qdrant-v8gc8cc4sk80o444ccck0gkg.178.16.129.71.sslip.io
      - QDRANT_API_KEY=obuONHxVHnSKivuN9Q5xqZGqtERfc2KM
      - COLLECTION_NAME=ClaudeCollection
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - IGNORE_CONNECTION_ERROR=true
    ports:
      - "8000:8000"
    restart: unless-stopped